/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SlotsRouteImport } from './routes/slots'
import { Route as MockTestsRouteImport } from './routes/mock-tests'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentsIndexRouteImport } from './routes/students.index'
import { Route as StudentsIdRouteImport } from './routes/students.$id'

const SlotsRoute = SlotsRouteImport.update({
  id: '/slots',
  path: '/slots',
  getParentRoute: () => rootRouteImport,
} as any)
const MockTestsRoute = MockTestsRouteImport.update({
  id: '/mock-tests',
  path: '/mock-tests',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIdRoute = StudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/attendance': typeof AttendanceRoute
  '/mock-tests': typeof MockTestsRoute
  '/slots': typeof SlotsRoute
  '/students/$id': typeof StudentsIdRoute
  '/students/': typeof StudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/attendance': typeof AttendanceRoute
  '/mock-tests': typeof MockTestsRoute
  '/slots': typeof SlotsRoute
  '/students/$id': typeof StudentsIdRoute
  '/students': typeof StudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/attendance': typeof AttendanceRoute
  '/mock-tests': typeof MockTestsRoute
  '/slots': typeof SlotsRoute
  '/students/$id': typeof StudentsIdRoute
  '/students/': typeof StudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/attendance'
    | '/mock-tests'
    | '/slots'
    | '/students/$id'
    | '/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/attendance'
    | '/mock-tests'
    | '/slots'
    | '/students/$id'
    | '/students'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/attendance'
    | '/mock-tests'
    | '/slots'
    | '/students/$id'
    | '/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AttendanceRoute: typeof AttendanceRoute
  MockTestsRoute: typeof MockTestsRoute
  SlotsRoute: typeof SlotsRoute
  StudentsIdRoute: typeof StudentsIdRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/slots': {
      id: '/slots'
      path: '/slots'
      fullPath: '/slots'
      preLoaderRoute: typeof SlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-tests': {
      id: '/mock-tests'
      path: '/mock-tests'
      fullPath: '/mock-tests'
      preLoaderRoute: typeof MockTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/': {
      id: '/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$id': {
      id: '/students/$id'
      path: '/students/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof StudentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  AttendanceRoute: AttendanceRoute,
  MockTestsRoute: MockTestsRoute,
  SlotsRoute: SlotsRoute,
  StudentsIdRoute: StudentsIdRoute,
  StudentsIndexRoute: StudentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
